# Generated by Django 4.2.3 on 2023-07-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IDp', models.IntegerField(primary_key=True, serialize=False)),
                ('Descrip', models.CharField(max_length=200)),
                ('Price', models.FloatField(blank=True)),
                ('Obs', models.CharField(max_length=200)),
                ('Stock', models.FloatField(blank=True)),
                ('Sold', models.FloatField(blank=True)),
                ('URLimg', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lista_productos',
            },
        ),
    ]
